"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name, default):
    value = os.environ.get(name)
    if value is None:
        return default
    try:
        return int(value.strip())
    except (TypeError, ValueError):
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local
    "organizations",
    "extension",
    "gamification",
    "phishing",
    "agent",
    "datawarehouse",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "organizations.Organization"

# Supabase
SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY")

# -----------------------------------------------------------------
# Email / SMTP
# Set these in your .env file.
#
# Example for Gmail:
#   EMAIL_HOST=smtp.gmail.com
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=you@gmail.com
#   EMAIL_HOST_PASSWORD=your-app-password
#   EMAIL_USE_TLS=True
#
# Example for SendGrid:
#   EMAIL_HOST=smtp.sendgrid.net
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=apikey
#   EMAIL_HOST_PASSWORD=SG.xxxxx
#   EMAIL_USE_TLS=True
#
# PHISHING_BASE_URL is the public-facing base URL of this backend,
# used to build click-tracking links in simulation emails.
#   PHISHING_BASE_URL=https://yourdomain.com
# -----------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False") == "True"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

PHISHING_BASE_URL = os.environ.get("PHISHING_BASE_URL", "http://localhost:8000")

EXTENSION_BLACKLIST_DOMAINS = [
    "malware-test.local",
    "credential-harvest-test.local",
    "eicar.org",
]

EXTENSION_AI_TARGET_DOMAINS = [
    "chat.openai.com",
    "chatgpt.com",
    "claude.ai",
    "gemini.google.com",
    "copilot.microsoft.com",
]

EXTENSION_AI_TARGET_KEYWORDS = [
    "chatgpt",
    "claude",
    "gemini",
    "copilot",
    "ai chat",
    "assistant",
    "prompt",
]

REPUTATION_GOOGLE_SAFE_BROWSING_ENABLED = _env_bool(
    "REPUTATION_GOOGLE_SAFE_BROWSING_ENABLED",
    default=False,
)
GOOGLE_SAFE_BROWSING_API_KEY = os.environ.get("GOOGLE_SAFE_BROWSING_API_KEY", "")
REPUTATION_CHECK_TIMEOUT_MS = _env_int("REPUTATION_CHECK_TIMEOUT_MS", 2000)

REPUTATION_PHISHTANK_ENABLED = _env_bool("REPUTATION_PHISHTANK_ENABLED", default=True)
REPUTATION_OPENPHISH_ENABLED = _env_bool("REPUTATION_OPENPHISH_ENABLED", default=True)
REPUTATION_URLHAUS_ENABLED = _env_bool("REPUTATION_URLHAUS_ENABLED", default=True)

REPUTATION_PHISHTANK_FEED_URL = os.environ.get(
    "REPUTATION_PHISHTANK_FEED_URL",
    "https://data.phishtank.com/data/online-valid.csv",
)
REPUTATION_OPENPHISH_FEED_URL = os.environ.get(
    "REPUTATION_OPENPHISH_FEED_URL",
    "https://openphish.com/feed.txt",
)
REPUTATION_URLHAUS_FEED_URL = os.environ.get(
    "REPUTATION_URLHAUS_FEED_URL",
    "https://urlhaus.abuse.ch/downloads/csv_online/",
)

REPUTATION_PHISHTANK_REFRESH_SECONDS = _env_int(
    "REPUTATION_PHISHTANK_REFRESH_SECONDS",
    3600,
)
REPUTATION_OPENPHISH_REFRESH_SECONDS = _env_int(
    "REPUTATION_OPENPHISH_REFRESH_SECONDS",
    1800,
)
REPUTATION_URLHAUS_REFRESH_SECONDS = _env_int(
    "REPUTATION_URLHAUS_REFRESH_SECONDS",
    1800,
)
