import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CiscoDevice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("device_type", models.CharField(choices=[("router","Router"),("switch","Switch"),("firewall","Firewall"),("ap","Access Point"),("other","Other")], default="router", max_length=20)),
                ("model", models.CharField(blank=True, default="", max_length=255)),
                ("serial_number", models.CharField(blank=True, default="", max_length=100)),
                ("ios_version", models.CharField(blank=True, default="", max_length=100)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("snmp_community", models.CharField(default="public", max_length=100)),
                ("snmp_version", models.CharField(default="2c", max_length=10)),
                ("snmp_port", models.IntegerField(default=161)),
                ("ssh_username", models.CharField(blank=True, default="", max_length=100)),
                ("ssh_password", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("up","Up"),("down","Down"),("degraded","Degraded"),("unknown","Unknown")], default="unknown", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("last_polled", models.DateTimeField(blank=True, null=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cisco_devices", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"], "unique_together": {("organization", "ip_address")}},
        ),
        migrations.CreateModel(
            name="CiscoSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("collected_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("sys_uptime_seconds", models.BigIntegerField(blank=True, null=True)),
                ("sys_description", models.TextField(blank=True, default="")),
                ("sys_name", models.CharField(blank=True, default="", max_length=255)),
                ("sys_location", models.CharField(blank=True, default="", max_length=255)),
                ("cpu_usage_5s", models.FloatField(blank=True, null=True)),
                ("cpu_usage_1m", models.FloatField(blank=True, null=True)),
                ("cpu_usage_5m", models.FloatField(blank=True, null=True)),
                ("memory_used_bytes", models.BigIntegerField(blank=True, null=True)),
                ("memory_free_bytes", models.BigIntegerField(blank=True, null=True)),
                ("temperature_celsius", models.FloatField(blank=True, null=True)),
                ("temperature_status", models.CharField(blank=True, default="", max_length=50)),
                ("interface_count", models.IntegerField(blank=True, null=True)),
                ("interfaces_up", models.IntegerField(default=0)),
                ("interfaces_down", models.IntegerField(default=0)),
                ("total_in_octets", models.BigIntegerField(blank=True, null=True)),
                ("total_out_octets", models.BigIntegerField(blank=True, null=True)),
                ("total_in_errors", models.BigIntegerField(default=0)),
                ("total_out_errors", models.BigIntegerField(default=0)),
                ("total_in_discards", models.BigIntegerField(default=0)),
                ("bgp_peer_count", models.IntegerField(blank=True, null=True)),
                ("bgp_peers_established", models.IntegerField(blank=True, null=True)),
                ("ospf_neighbor_count", models.IntegerField(blank=True, null=True)),
                ("route_count", models.IntegerField(blank=True, null=True)),
                ("acl_violation_count", models.BigIntegerField(default=0)),
                ("failed_login_count", models.IntegerField(default=0)),
                ("arp_entry_count", models.IntegerField(blank=True, null=True)),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                ("risk_level", models.CharField(blank=True, default="", max_length=20)),
                ("risk_signals", models.JSONField(default=list)),
                ("anomaly_flags", models.JSONField(default=list)),
                ("interfaces_detail", models.JSONField(default=list)),
                ("raw", models.JSONField(default=dict)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="cisco.ciscodevice")),
            ],
            options={"ordering": ["-collected_at"]},
        ),
        migrations.CreateModel(
            name="CiscoConfigBackup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("config_type", models.CharField(choices=[("running","Running Config"),("startup","Startup Config")], default="running", max_length=10)),
                ("content", models.TextField()),
                ("checksum", models.CharField(max_length=64)),
                ("size_bytes", models.IntegerField()),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("changed_from_previous", models.BooleanField(default=False)),
                ("diff_summary", models.TextField(blank=True, default="")),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="config_backups", to="cisco.ciscodevice")),
            ],
            options={"ordering": ["-collected_at"]},
        ),
        migrations.CreateModel(
            name="CiscoSecurityAlert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("alert_type", models.CharField(max_length=30)),
                ("severity", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("recommendation", models.TextField(blank=True, default="")),
                ("ai_generated", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alerts", to="cisco.ciscodevice")),
                ("snapshot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="alerts", to="cisco.ciscosnapshot")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CiscoVulnerabilityCheck",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cve_id", models.CharField(max_length=50)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("severity", models.CharField(blank=True, max_length=20)),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True)),
                ("affected_versions", models.TextField(blank=True)),
                ("fix_available", models.BooleanField(default=False)),
                ("fix_version", models.CharField(blank=True, max_length=100)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vulnerability_checks", to="cisco.ciscodevice")),
            ],
            options={"ordering": ["-cvss_score"], "unique_together": {("device", "cve_id")}},
        ),
    ]