# Generated by Django 5.1.3 on 2026-05-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phishingtemplate",
            name="body",
            field=models.TextField(
                help_text="HTML or plain-text body. Use {{employee_name}} as a placeholder for the recipient's name and {{tracking_url}} for the click-tracking link."
            ),
        ),
        migrations.AlterField(
            model_name="phishingtemplate",
            name="sender_domain",
            field=models.CharField(
                help_text="Spoofed sender domain shown in the From header (e.g. it-support.company.com).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="trainingenrollment",
            name="simulation_target",
            field=models.ForeignKey(
                blank=True,
                help_text="The simulation click that triggered this enrollment, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_enrollments",
                to="phishing.phishingsimulationtarget",
            ),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="content",
            field=models.TextField(
                help_text="Plain-text or Markdown content of the micro-training module."
            ),
        ),
    ]
