# Generated by Django 5.1.3 on 2026-05-02 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(choices=[("QUIZ", "Quiz")], max_length=20),
                ),
                (
                    "payload",
                    models.JSONField(help_text="For QUIZ: {question, options}."),
                ),
                ("is_delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_events",
                        to="organizations.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlacklistLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempted_url", models.URLField(max_length=2048)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_logs",
                        to="organizations.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DLPLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("website", models.URLField(max_length=2048)),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("cancel", "Cancel"),
                            ("force", "Force"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "event_channel",
                    models.CharField(
                        choices=[
                            ("file_upload", "File Upload"),
                            ("ai_prompt", "AI Prompt"),
                        ],
                        default="file_upload",
                        max_length=32,
                    ),
                ),
                ("document_topic", models.TextField(blank=True, default="")),
                ("semantic_score", models.FloatField(blank=True, null=True)),
                (
                    "detection_tier",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("detection_reason", models.TextField(blank=True, default="")),
                (
                    "matched_pattern",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("input_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("input_size_chars", models.IntegerField(blank=True, null=True)),
                (
                    "threshold_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("decision_score", models.FloatField(blank=True, null=True)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dlp_logs",
                        to="organizations.employee",
                    ),
                ),
            ],
        ),
    ]
