# Generated by Django 5.1.3 on 2026-05-02 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_remove_organization_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("QUIZ", "Quiz"), ("FAKE_PHISHING", "Fake Phishing")],
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="For QUIZ: {question, options}. For FAKE_PHISHING: leave empty ({})."
                    ),
                ),
                ("is_delivered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_events",
                        to="organizations.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlacklistLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempted_url", models.URLField(max_length=2048)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_logs",
                        to="organizations.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DLPLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("website", models.URLField(max_length=2048)),
                (
                    "action_taken",
                    models.CharField(
                        choices=[("BLOCKED", "Blocked"), ("BYPASSED", "Bypassed")],
                        max_length=10,
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dlp_logs",
                        to="organizations.device",
                    ),
                ),
            ],
        ),
    ]
