# Generated by Django 6.0.4 on 2026-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extension", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dlplog",
            name="decision_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="detection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="detection_tier",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="document_topic",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="event_channel",
            field=models.CharField(
                choices=[("file_upload", "File Upload"), ("ai_prompt", "AI Prompt")],
                default="file_upload",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="input_size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="input_size_chars",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="matched_pattern",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="semantic_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="threshold_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dlplog",
            name="threshold_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
