# Generated by Django 5.1.3 on 2026-05-02 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="user_permissions",
        ),
    ]
