# Generated by Django 5.1.3 on 2026-05-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_authtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthToken",
        ),
    ]
