# Generated by Django 5.1.3 on 2026-05-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_delete_authtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="supabase_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
