# Generated by Django 5.1.3 on 2026-05-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_organization_supabase_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="supabase_id",
        ),
        migrations.AddField(
            model_name="organization",
            name="supabase_uid",
            field=models.UUIDField(
                blank=True,
                help_text="Supabase Auth user ID (sub claim in JWT)",
                null=True,
                unique=True,
            ),
        ),
    ]
