# Generated by Django 5.1.3 on 2026-05-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_remove_organization_supabase_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
