# Generated by Django 6.0.4 on 2026-05-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = []
