# Generated by Django 5.1.3 on 2026-05-02 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0010_employee_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collected_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                ("os_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "os_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "architecture",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("uptime_seconds", models.BigIntegerField(blank=True, null=True)),
                ("cpu_cores", models.IntegerField(blank=True, null=True)),
                ("total_memory_mb", models.IntegerField(blank=True, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("local_admin_count", models.IntegerField(default=0)),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("risk_signals", models.JSONField(default=list)),
                ("raw", models.JSONField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="organizations.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-collected_at"],
                        name="agent_devic_employe_2a9d7d_idx",
                    ),
                    models.Index(
                        fields=["hostname"], name="agent_devic_hostnam_463a2a_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="agent_devic_risk_le_585441_idx"
                    ),
                ],
            },
        ),
    ]
