# Generated by Django 5.1.3 on 2026-05-02 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0007_organization_is_staff_organization_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedSoftware",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_software",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="agent_appro_organiz_6a5cf3_idx"
                    )
                ],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.CreateModel(
            name="DeviceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collected_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                ("os_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "os_version",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("os_build", models.CharField(blank=True, default="", max_length=50)),
                ("cpu_model", models.CharField(blank=True, default="", max_length=255)),
                ("ram_total_mb", models.IntegerField(blank=True, null=True)),
                ("disk_total_gb", models.FloatField(blank=True, null=True)),
                ("disk_free_gb", models.FloatField(blank=True, null=True)),
                (
                    "machine_uuid",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "primary_mac",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("patch_is_current", models.BooleanField(blank=True, null=True)),
                ("patch_last_updated", models.DateField(blank=True, null=True)),
                ("patch_days_since_update", models.IntegerField(blank=True, null=True)),
                ("antivirus_detected", models.BooleanField(blank=True, null=True)),
                (
                    "antivirus_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("antivirus_enabled", models.BooleanField(blank=True, null=True)),
                ("antivirus_up_to_date", models.BooleanField(blank=True, null=True)),
                ("disk_encrypted", models.BooleanField(blank=True, null=True)),
                ("usb_enabled", models.BooleanField(blank=True, null=True)),
                ("lan_device_count", models.IntegerField(blank=True, null=True)),
                ("local_port_count", models.IntegerField(blank=True, null=True)),
                ("wifi_open_network_count", models.IntegerField(default=0)),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("risk_signals", models.JSONField(default=list)),
                ("raw", models.JSONField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="organizations.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-collected_at"],
                        name="agent_devic_employe_2a9d7d_idx",
                    ),
                    models.Index(
                        fields=["hostname"], name="agent_devic_hostnam_463a2a_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="agent_devic_risk_le_585441_idx"
                    ),
                ],
            },
        ),
    ]
