# Generated by Django 5.1.3 on 2026-05-02 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiskHealthSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collected_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                (
                    "device_path",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("model", models.CharField(blank=True, default="", max_length=255)),
                ("serial", models.CharField(blank=True, default="", max_length=100)),
                ("capacity_gb", models.FloatField(blank=True, null=True)),
                ("disk_type", models.CharField(blank=True, default="", max_length=20)),
                (
                    "smart_health",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("reallocated_sectors", models.IntegerField(blank=True, null=True)),
                ("pending_sectors", models.IntegerField(blank=True, null=True)),
                ("uncorrectable_errors", models.IntegerField(blank=True, null=True)),
                ("power_on_hours", models.IntegerField(blank=True, null=True)),
                ("temperature_c", models.IntegerField(blank=True, null=True)),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                ("risk_level", models.CharField(blank=True, default="", max_length=20)),
                ("risk_signals", models.JSONField(default=list)),
                ("raw", models.JSONField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disk_health_snapshots",
                        to="organizations.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-collected_at"],
                        name="agent_diskh_employe_aa0f9c_idx",
                    ),
                    models.Index(
                        fields=["smart_health"], name="agent_diskh_smart_h_244b40_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="agent_diskh_risk_le_9c484f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NetworkDeviceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collected_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("device_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "device_hostname",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("vendor", models.CharField(blank=True, default="", max_length=100)),
                ("sys_description", models.TextField(blank=True, default="")),
                ("interface_count", models.IntegerField(blank=True, null=True)),
                ("interfaces_down", models.IntegerField(default=0)),
                ("high_error_interfaces", models.IntegerField(default=0)),
                ("total_in_bytes", models.BigIntegerField(blank=True, null=True)),
                ("total_out_bytes", models.BigIntegerField(blank=True, null=True)),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                ("risk_level", models.CharField(blank=True, default="", max_length=20)),
                ("risk_signals", models.JSONField(default=list)),
                ("raw", models.JSONField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_snapshots",
                        to="organizations.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-collected_at"],
                        name="agent_netwo_employe_2bbc08_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="agent_netwo_risk_le_865e12_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemMetricsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collected_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                ("cpu_usage_percent", models.FloatField(blank=True, null=True)),
                ("cpu_cores", models.IntegerField(blank=True, null=True)),
                ("cpu_load_1m", models.FloatField(blank=True, null=True)),
                ("cpu_load_5m", models.FloatField(blank=True, null=True)),
                ("cpu_load_15m", models.FloatField(blank=True, null=True)),
                ("ram_total_mb", models.IntegerField(blank=True, null=True)),
                ("ram_used_mb", models.IntegerField(blank=True, null=True)),
                ("ram_usage_percent", models.FloatField(blank=True, null=True)),
                ("swap_usage_percent", models.FloatField(blank=True, null=True)),
                ("process_count", models.IntegerField(blank=True, null=True)),
                ("zombie_process_count", models.IntegerField(default=0)),
                ("high_cpu_processes", models.JSONField(default=list)),
                ("risk_score", models.IntegerField(blank=True, null=True)),
                ("risk_level", models.CharField(blank=True, default="", max_length=20)),
                ("risk_signals", models.JSONField(default=list)),
                ("raw", models.JSONField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_metrics_snapshots",
                        to="organizations.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "-collected_at"],
                        name="agent_syste_employe_f949c7_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="agent_syste_risk_le_b4f4e9_idx"
                    ),
                ],
            },
        ),
    ]
