# Generated by Django 6.0.4 on 2026-05-02 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0002_add_employee_and_employeeauthtoken"),
        ("organizations", "0008_add_employee_and_employeeauthtoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsubmission",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_submissions",
                to="organizations.employee",
            ),
        ),
        migrations.AddField(
            model_name="quizbatch",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quizbatch",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="gamification.quiz",
            ),
        ),
        migrations.AddField(
            model_name="quizbatchassignment",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="gamification.quizbatch",
            ),
        ),
        migrations.AddField(
            model_name="quizbatchassignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_batch_assignments",
                to="organizations.employee",
            ),
        ),
        migrations.AddField(
            model_name="quizbatch",
            name="employees",
            field=models.ManyToManyField(
                related_name="quiz_batches",
                through="gamification.QuizBatchAssignment",
                to="organizations.employee",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizbatchassignment",
            unique_together={("batch", "employee")},
        ),
    ]
